<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New Student RegistrationCreate your Mob_4c9450</name>
   <tag></tag>
   <elementGuidId>291dc209-5542-411a-ad4e-67ba1d61cfd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='registerCard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#registerCard</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>169cbbe2-da6f-442b-9ae0-a0429764f83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root mainCard1 css-1p4az8h</value>
      <webElementGuid>6d4de0b6-528f-4c4b-989a-dbc9a4e64dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerCard</value>
      <webElementGuid>ca6ec6bf-204e-4f38-b38b-7522701ddebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Student RegistrationCreate your Mobile MyTix Student Monthly Pass account with these simple steps.* Denotes required fieldsFirst Name *​Last Name *​Email *​Confirm Email *​Password *​Confirm Password *​Phone *​Country *​Zip/Postal Code *​Date Of Birth (MM/DD)​1. Fill in all required fields on the registration form.2. Verify your student email address. 3. Download the NJ TRANSIT App and buy your Mobile MyTix Student Monthly Pass.Student Monthly Pass FAQs.Terms of Use The student monthly pass is for the personal use of the student who purchased it and is restricted for use traveling to/from stations indicated on the pass for the sole purpose of attending school. Student passes are not honored to or from any other rail station except those printed on the pass. But they may be used on certain buses and light rail vehicles as permitted under NJ TRANSIT cross-honoring policies. Details are available in the ‘Travel Flexibility’ section of the    train,  bus  or  light rail  ticket webpages. NJ TRANSIT reserves the right to review the applications for student passes. To ensure compliance with NJ TRANSIT policies, Students must present their student identification card upon request by train crew personnel or any NJ TRANSIT representative.Note: Password is case sensitive and must be at least 8 characters and contain at least one lowercase letter, one uppercase letter, one number, and one symbol from the following ~`!@#$%^&amp;*()_-+={[}]|\:&quot;&lt;,>.?/submit</value>
      <webElementGuid>4623f637-38a2-42f7-8d4a-a704294e9754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerCard&quot;)</value>
      <webElementGuid>e1273feb-8ccf-405f-a101-7f8ee8d86e96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='registerCard']</value>
      <webElementGuid>b2036f91-e91d-403e-8abd-2d84eabe0d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div</value>
      <webElementGuid>9ca58ebf-eaaa-471a-99c8-71a3dc921ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::div[5]</value>
      <webElementGuid>72a82487-97d1-4e73-92a3-7895d63106c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::div[5]</value>
      <webElementGuid>b94560f9-a87e-494d-bced-91c9b51aa8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>157c1fb3-3c8e-42f4-a2bc-368c28e90f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'registerCard' and (text() = 'New Student RegistrationCreate your Mobile MyTix Student Monthly Pass account with these simple steps.* Denotes required fieldsFirst Name *​Last Name *​Email *​Confirm Email *​Password *​Confirm Password *​Phone *​Country *​Zip/Postal Code *​Date Of Birth (MM/DD)​1. Fill in all required fields on the registration form.2. Verify your student email address. 3. Download the NJ TRANSIT App and buy your Mobile MyTix Student Monthly Pass.Student Monthly Pass FAQs.Terms of Use The student monthly pass is for the personal use of the student who purchased it and is restricted for use traveling to/from stations indicated on the pass for the sole purpose of attending school. Student passes are not honored to or from any other rail station except those printed on the pass. But they may be used on certain buses and light rail vehicles as permitted under NJ TRANSIT cross-honoring policies. Details are available in the ‘Travel Flexibility’ section of the    train,  bus  or  light rail  ticket webpages. NJ TRANSIT reserves the right to review the applications for student passes. To ensure compliance with NJ TRANSIT policies, Students must present their student identification card upon request by train crew personnel or any NJ TRANSIT representative.Note: Password is case sensitive and must be at least 8 characters and contain at least one lowercase letter, one uppercase letter, one number, and one symbol from the following ~`!@#$%^&amp;*()_-+={[}]|\:&quot;&lt;,>.?/submit' or . = 'New Student RegistrationCreate your Mobile MyTix Student Monthly Pass account with these simple steps.* Denotes required fieldsFirst Name *​Last Name *​Email *​Confirm Email *​Password *​Confirm Password *​Phone *​Country *​Zip/Postal Code *​Date Of Birth (MM/DD)​1. Fill in all required fields on the registration form.2. Verify your student email address. 3. Download the NJ TRANSIT App and buy your Mobile MyTix Student Monthly Pass.Student Monthly Pass FAQs.Terms of Use The student monthly pass is for the personal use of the student who purchased it and is restricted for use traveling to/from stations indicated on the pass for the sole purpose of attending school. Student passes are not honored to or from any other rail station except those printed on the pass. But they may be used on certain buses and light rail vehicles as permitted under NJ TRANSIT cross-honoring policies. Details are available in the ‘Travel Flexibility’ section of the    train,  bus  or  light rail  ticket webpages. NJ TRANSIT reserves the right to review the applications for student passes. To ensure compliance with NJ TRANSIT policies, Students must present their student identification card upon request by train crew personnel or any NJ TRANSIT representative.Note: Password is case sensitive and must be at least 8 characters and contain at least one lowercase letter, one uppercase letter, one number, and one symbol from the following ~`!@#$%^&amp;*()_-+={[}]|\:&quot;&lt;,>.?/submit')]</value>
      <webElementGuid>7bfebc2e-daa6-4be4-94a8-370b992a5435</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
