<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_Once I have completed my enrollment, how_923b30</name>
   <tag></tag>
   <elementGuidId>1b286c16-a341-4a2c-be8b-97085e89a7a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#title7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h6[@id='title7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Once I have completed my enrollment, how do I purchase my student monthly pass in subsequent months?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>5c78bc92-4378-431d-ba6b-bc7efef2f284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-subtitle1 css-1c5co21</value>
      <webElementGuid>b3f4f689-2fdd-445c-933c-505d9ff2246a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title7</value>
      <webElementGuid>3ac60640-bc48-452a-918c-7832495f1579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Once I have completed my enrollment, how do I purchase my student monthly pass in subsequent months?</value>
      <webElementGuid>9ff48e58-6ff4-46c3-818c-2df5674cff8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title7&quot;)</value>
      <webElementGuid>273f465a-3d79-4b15-be98-2e4da29e03b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h6[@id='title7']</value>
      <webElementGuid>5f44a679-5a4e-44d4-902b-76c72bf9c19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='faqModal']/div[3]/div/div[2]/div/div[6]/h6</value>
      <webElementGuid>cfaa2dbc-c54f-4edd-b563-99ebc4620787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How do I purchase my first mobile Student Monthly Pass?'])[1]/following::h6[1]</value>
      <webElementGuid>7e63998a-3080-4fde-9be6-a148ebe711d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where can I use a Student Monthly Pass?'])[1]/following::h6[2]</value>
      <webElementGuid>b5faa106-5ecd-401d-a766-bdc49a841f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do I have to renew my Student Pass account at any time?'])[1]/preceding::h6[1]</value>
      <webElementGuid>53bce14e-1f7f-45b9-b527-b37b80180123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When can I purchase my student monthly pass?'])[1]/preceding::h6[2]</value>
      <webElementGuid>e3674e0a-a47a-4530-8782-25ca018b51a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Once I have completed my enrollment, how do I purchase my student monthly pass in subsequent months?']/parent::*</value>
      <webElementGuid>0c4b98fa-532d-4beb-8694-2261bc33de18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/h6</value>
      <webElementGuid>0d439194-47ce-41d5-b573-ba146cdb7556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[@id = 'title7' and (text() = 'Once I have completed my enrollment, how do I purchase my student monthly pass in subsequent months?' or . = 'Once I have completed my enrollment, how do I purchase my student monthly pass in subsequent months?')]</value>
      <webElementGuid>4502a037-e803-4159-98cd-a615ad77b331</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
