<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Us_flex-auto rounded-md borde_d34ab1_1_2 (1)</name>
   <tag></tag>
   <elementGuidId>9476eccb-2dcf-4d85-b66a-f19f7335af98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='testde']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;view-this-mailbox&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a32fcef-204a-462e-a3e7-8367ebecded0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23d6f623-5fb5-47af-ba8c-34ced114e15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>view-this-mailbox</value>
      <webElementGuid>20666310-14c8-4506-9f65-bb4307b90af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>dafa2dbc-089f-447f-a449-c28297e7ff69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-auto rounded-md border-stone-400 bg-white py-2 px-2 text-right text-base text-stone-900 placeholder-stone-400 focus:border-white focus:placeholder-stone-300 focus:ring-[3px] focus:ring-rose-500/80 dark:border-stone-500 dark:bg-stone-800/95 dark:text-stone-50 dark:focus:border-stone-900 dark:focus:placeholder-stone-600 dark:focus:ring-rose-600/80</value>
      <webElementGuid>254bd8dc-677c-4a36-82a4-c6cc56a809c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>testde</value>
      <webElementGuid>696ebecd-0b57-4c68-a89c-f08567df5a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;flex flex-wrap items-center md:container md:mx-auto md:flex-nowrap md:px-4 md:py-2 lg:px-8&quot;]/div[@class=&quot;hidden absolute top-16 z-10 w-full flex-none bg-stone-100 pt-4 pb-16 dark:bg-stone-800 md:relative md:top-auto md:flex md:w-auto md:flex-auto md:items-center md:bg-transparent md:pt-0 md:pb-0 md:pl-4&quot;]/form[@class=&quot;px-8 md:px-0 lg:max-w-[50ch] flex flex-auto flex-wrap md:flex-nowrap&quot;]/div[@class=&quot;flex flex-auto flex-nowrap items-center&quot;]/input[@class=&quot;flex-auto rounded-md border-stone-400 bg-white py-2 px-2 text-right text-base text-stone-900 placeholder-stone-400 focus:border-white focus:placeholder-stone-300 focus:ring-[3px] focus:ring-rose-500/80 dark:border-stone-500 dark:bg-stone-800/95 dark:text-stone-50 dark:focus:border-stone-900 dark:focus:placeholder-stone-600 dark:focus:ring-rose-600/80&quot;]</value>
      <webElementGuid>a448d841-257f-4022-9d51-509e42280976</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='testde']</value>
      <webElementGuid>5fe92eae-eb0c-4119-a215-4a1b9ebeaf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div/div[3]/form/div/input</value>
      <webElementGuid>7cbcdb98-987c-4b42-98e8-36ee78451891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>67dfd0d5-b256-4235-b2d5-0f41ef294b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'view-this-mailbox']</value>
      <webElementGuid>4ad49ddd-67b7-4042-90de-2445a98ec983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
