<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Us_flex-auto rounded-md borde_d34ab1 (1)</name>
   <tag></tag>
   <elementGuidId>53e9ee10-cb85-4e0e-ba69-916074ad01c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='test']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;view-this-mailbox&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6eca23d0-c00a-4899-b898-fcef94901a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d76d0e3c-de37-4f7a-8e51-d0c9055cf66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>view-this-mailbox</value>
      <webElementGuid>29cf4134-d4ca-46fa-80ce-643b252b291f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>afd23ce4-748d-4c5c-86a5-2fb00220ce00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-auto rounded-md border-stone-400 bg-white py-2 px-2 text-right text-base text-stone-900 placeholder-stone-400 focus:border-white focus:placeholder-stone-300 focus:ring-[3px] focus:ring-rose-500/80 dark:border-stone-500 dark:bg-stone-800/95 dark:text-stone-50 dark:focus:border-stone-900 dark:focus:placeholder-stone-600 dark:focus:ring-rose-600/80</value>
      <webElementGuid>9a3c0fe0-426a-4558-a78a-f91542111d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>401e1b2f-bc4f-461d-aa64-1c4f7396aa38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;flex flex-wrap items-center md:container md:mx-auto md:flex-nowrap md:px-4 md:py-2 lg:px-8&quot;]/div[@class=&quot;hidden absolute top-16 z-10 w-full flex-none bg-stone-100 pt-4 pb-16 dark:bg-stone-800 md:relative md:top-auto md:flex md:w-auto md:flex-auto md:items-center md:bg-transparent md:pt-0 md:pb-0 md:pl-4&quot;]/form[@class=&quot;px-8 md:px-0 lg:max-w-[50ch] flex flex-auto flex-wrap md:flex-nowrap&quot;]/div[@class=&quot;flex flex-auto flex-nowrap items-center&quot;]/input[@class=&quot;flex-auto rounded-md border-stone-400 bg-white py-2 px-2 text-right text-base text-stone-900 placeholder-stone-400 focus:border-white focus:placeholder-stone-300 focus:ring-[3px] focus:ring-rose-500/80 dark:border-stone-500 dark:bg-stone-800/95 dark:text-stone-50 dark:focus:border-stone-900 dark:focus:placeholder-stone-600 dark:focus:ring-rose-600/80&quot;]</value>
      <webElementGuid>ff976e2d-539e-4836-8e04-128ddce5f4b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='test']</value>
      <webElementGuid>9de0a27a-9a23-4bd4-be9d-eb2c1ea74a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div/div[3]/form/div/input</value>
      <webElementGuid>695066ac-d148-4d88-99e4-33fecb97b7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>88f41690-3458-4515-baa4-bfa8de7cee2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'view-this-mailbox']</value>
      <webElementGuid>aa8af219-fbdf-47de-bd44-797a6083bb98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
