<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Search_visa</name>
   <tag></tag>
   <elementGuidId>e3674ddd-5506-4021-b85f-f5c0f9e9f1e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#visa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='visa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#visa</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f2934eb9-af61-4e82-b10d-8b59ef8ad5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-v7v99c</value>
      <webElementGuid>68cf4a8a-ecd8-48f9-b436-b22e21946542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visa</value>
      <webElementGuid>a2cf4ba1-7f36-4d7b-ab0b-415d69fe00ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/admin-portal/static/media/visa_card.abc64a7a194ed23216e1.png</value>
      <webElementGuid>b4f85db7-e818-40fd-ad17-1c6b75978ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visa&quot;)</value>
      <webElementGuid>b6ef988c-8775-4b7e-b27f-aed86c26680b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='visa']</value>
      <webElementGuid>ac0cdea1-25ff-4c01-9707-2f857caf548c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'visa' and @src = '/admin-portal/static/media/visa_card.abc64a7a194ed23216e1.png']</value>
      <webElementGuid>ff0fa2e3-f111-42b9-b8fe-2ee0258d3609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SearchPaygoInfo']/div/div/div/div/img</value>
      <webElementGuid>e59d847e-b0fc-40cb-b63f-c17a64d9888c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/img</value>
      <webElementGuid>fd211202-3579-42b0-a4bf-1400b2747587</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
