<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Us_flex-auto rounded-md borde_d34ab1_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>e1892e11-f9af-4564-bd2c-f0637a5b95d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='rashmi.k']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#navbar >> internal:attr=[placeholder=&quot;view-this-mailbox&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a40441e9-9bea-44de-819a-e8f7809f52bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>010e7714-01fd-4583-b795-f670f37d8a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>view-this-mailbox</value>
      <webElementGuid>5ae41465-1d9a-49c9-848f-fbf1fb9ddb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>feb6c331-fbc3-48de-91ff-16353319ddea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-auto rounded-md border-stone-400 bg-white py-2 px-2 text-right text-base text-stone-900 placeholder-stone-400 focus:border-white focus:placeholder-stone-300 focus:ring-[3px] focus:ring-rose-500/80 dark:border-stone-500 dark:bg-stone-800/95 dark:text-stone-50 dark:focus:border-stone-900 dark:focus:placeholder-stone-600 dark:focus:ring-rose-600/80</value>
      <webElementGuid>a98b41dd-bc5a-44fe-aeb7-cc7929ff072f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>rashmi.k</value>
      <webElementGuid>b31328dc-64d3-4bfa-b781-ac85db00a17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;flex flex-wrap items-center md:container md:mx-auto md:flex-nowrap md:px-4 md:py-2 lg:px-8&quot;]/div[@class=&quot;hidden absolute top-16 z-10 w-full flex-none bg-stone-100 pt-4 pb-16 dark:bg-stone-800 md:relative md:top-auto md:flex md:w-auto md:flex-auto md:items-center md:bg-transparent md:pt-0 md:pb-0 md:pl-4&quot;]/form[@class=&quot;px-8 md:px-0 lg:max-w-[50ch] flex flex-auto flex-wrap md:flex-nowrap&quot;]/div[@class=&quot;flex flex-auto flex-nowrap items-center&quot;]/input[@class=&quot;flex-auto rounded-md border-stone-400 bg-white py-2 px-2 text-right text-base text-stone-900 placeholder-stone-400 focus:border-white focus:placeholder-stone-300 focus:ring-[3px] focus:ring-rose-500/80 dark:border-stone-500 dark:bg-stone-800/95 dark:text-stone-50 dark:focus:border-stone-900 dark:focus:placeholder-stone-600 dark:focus:ring-rose-600/80&quot;]</value>
      <webElementGuid>e20389db-31e9-4bd5-a1a5-71eca648b029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='rashmi.k']</value>
      <webElementGuid>f397ffe3-b77c-40c3-b670-ee33d241b527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'view-this-mailbox']</value>
      <webElementGuid>71cb9a55-60d2-47f7-bda5-f98092705efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div/div[3]/form/div/input</value>
      <webElementGuid>fd7d65c0-d0ad-4106-82f8-aa1d582d78ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>333d9c28-1e9f-48dd-be68-21247e790f76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
