<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Cardholder, , s Name)_ccHolderName</name>
   <tag></tag>
   <elementGuidId>efb0ce82-e5ec-485e-8aa0-46f6584d14f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ccHolderName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ccHolderName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Cardholder's Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>008efa45-1ad3-4fe3-9ad6-b51edd35066b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9831c6a6-6db0-4202-94ff-7d48b6ee04ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-name</value>
      <webElementGuid>f63fb25a-d86c-40f5-9a2b-e28ffcaa6480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ccHolderName</value>
      <webElementGuid>b3ca4cb6-9bb2-477f-a522-e8d5712e1d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ccHolderName</value>
      <webElementGuid>b914ba89-c75a-4720-8ab2-88fb8b148b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cardholder's Name</value>
      <webElementGuid>3c2c71da-46ef-4cc4-b1d0-2c9de0109775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c4622b9-3baa-4bce-925f-950799c06378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3cb6e3df-738c-4259-9668-490b69828759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>2c3a8552-5701-4a01-811b-07d731f8b4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Cardholder's Name  *</value>
      <webElementGuid>a77978e8-8494-4191-bc25-7a0e7cae6dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>36e6a37b-47a6-4a1c-9b6e-e5697c3320bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>838dd313-c998-43f1-bd19-37af5972ebc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-162ofju</value>
      <webElementGuid>739ae74e-621e-4d53-bc2c-9ca2acf32858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccHolderName&quot;)</value>
      <webElementGuid>f415b085-926a-461b-8a2a-a4067e445c17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ccHolderName']</value>
      <webElementGuid>f7dd5afc-d2cb-4602-b86e-c4d99554646c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ccHolderName' and @name = 'ccHolderName' and @placeholder = concat(&quot;Cardholder&quot; , &quot;'&quot; , &quot;s Name&quot;) and @type = 'text']</value>
      <webElementGuid>fc204146-9c3b-47ef-ba1f-73feeb2819c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='patDebtForm']/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>3f4395b5-92a4-49a7-b554-5c1f99e1b561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>7a80d124-52a9-421e-8b1b-be8c47427562</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
