<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_light rail</name>
   <tag></tag>
   <elementGuidId>15c9d246-51dd-4803-a6c8-b562343289cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#desc11 > span > a:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='desc11']/span/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;light rail&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2962af6-5b77-452a-b1f6-3dc8a2ba0dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.njtransit.com/tickets/light-rail-tickets</value>
      <webElementGuid>6a273d0f-abdd-44b9-a9a8-f43f34788377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>fe6a83f8-2601-47af-a1ab-dda87d218f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>light rail </value>
      <webElementGuid>e2ce5331-43ad-45ca-b5e7-60922d741be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desc11&quot;)/span[1]/a[3]</value>
      <webElementGuid>42068a5d-9977-46c7-b529-80727f500645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='desc11']/span/a[3]</value>
      <webElementGuid>0e0e8f95-66c8-4f24-ba0d-9b1d89d27a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'light rail')])[2]</value>
      <webElementGuid>4c7ee1d6-9883-4309-91c0-973753479427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bus'])[2]/following::a[1]</value>
      <webElementGuid>55658672-ca04-4c4c-bb78-2b6bfe140c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rail'])[1]/following::a[2]</value>
      <webElementGuid>3adb8df9-c406-4412-896e-5980b9f7aec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::a[1]</value>
      <webElementGuid>1e80a716-1770-4af1-b3e9-99b3e4b7f63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.njtransit.com/tickets/light-rail-tickets')])[2]</value>
      <webElementGuid>7f2d534f-6216-4aa7-b9be-b380ce37c676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span/a[3]</value>
      <webElementGuid>923c8904-f72d-479b-b2a1-851578cf89af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.njtransit.com/tickets/light-rail-tickets' and (text() = 'light rail ' or . = 'light rail ')]</value>
      <webElementGuid>dbd44b08-4cce-41aa-885e-70d9c2a3121b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='studentDesc']/a[3]</value>
      <webElementGuid>6841a1a7-5d6d-4511-85ab-c9f0f19f519d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'light rail')]</value>
      <webElementGuid>b361d42b-7524-49c3-ba84-a495623ae1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bus'])[1]/following::a[1]</value>
      <webElementGuid>38e760be-868b-4b22-867b-4d389deafdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help &amp; Support'])[1]/preceding::a[1]</value>
      <webElementGuid>dc3071a1-dff2-4c18-ac3d-d6564b85e5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/preceding::a[2]</value>
      <webElementGuid>dc088d98-0567-4404-a5c7-df40dd3e6616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='light rail']/parent::*</value>
      <webElementGuid>61f33613-58b1-4432-88c2-425eb7bab11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.njtransit.com/tickets/light-rail-tickets')]</value>
      <webElementGuid>832423bb-a18b-46ef-a4f5-602143c44608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>58c92ef7-88b1-4380-962a-0fbea6644e3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
