<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Denotes required fields</name>
   <tag></tag>
   <elementGuidId>d548ff19-54ac-49bd-9e8c-8f1ffd033086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#requiredNote</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='requiredNote']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;* Denotes required fields&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9733c41f-edc0-401e-95da-964eaddc3e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-desc css-2ylu04</value>
      <webElementGuid>22e6a85f-285b-4f01-af38-601dd96efa88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requiredNote</value>
      <webElementGuid>604caebd-26dd-4b28-8a95-15bc3fcf08f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>* Denotes required fields</value>
      <webElementGuid>5ac72869-dbb3-4a5d-b731-92b9987b2aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requiredNote&quot;)</value>
      <webElementGuid>896a4f39-6ce2-4307-973a-8ea6bbfef3fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='requiredNote']</value>
      <webElementGuid>c8aefa6c-7cbd-4600-97ca-ac2db125c390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginCard']/div/div/div/div/span</value>
      <webElementGuid>769a3505-a556-4c89-beb2-150d88d506bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Login'])[1]/following::span[1]</value>
      <webElementGuid>d6de97f6-99fa-4065-9b24-f3df7d057866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::span[1]</value>
      <webElementGuid>57affde8-ad97-4ae6-9a73-34c3dc0d84d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you have an existing NJT account, please use your Email and Password to Sign In.'])[1]/preceding::span[2]</value>
      <webElementGuid>bbf9f82b-a86a-41b1-ab31-9535092cfc61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Denotes required fields']/parent::*</value>
      <webElementGuid>594cb4c6-8f8b-4e3b-9e22-fa5a37628127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>f0db68db-f19b-4518-aea9-9e710f9ccfdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'requiredNote' and (text() = '* Denotes required fields' or . = '* Denotes required fields')]</value>
      <webElementGuid>6410a3cf-7066-4d14-843f-bd9f57d2d07e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
