<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Student Monthly Pass FAQs</name>
   <tag></tag>
   <elementGuidId>4d7565bd-0f52-4b7e-91b7-eec9d9585c3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#studentTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='studentTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Student Monthly Pass FAQs.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b1a5f119-a8fa-4d57-8db1-5dac078f1368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-title MuiTypography-alignCenter css-gwxx20</value>
      <webElementGuid>cf47f8ef-ce1f-48e4-9edc-fb5e6968c6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>studentTitle</value>
      <webElementGuid>d9df25c5-8212-4a55-abc0-3d59e49c57db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Student Monthly Pass FAQs.</value>
      <webElementGuid>ddc3e271-92b5-4526-b107-6b827f46579b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;studentTitle&quot;)</value>
      <webElementGuid>b6b96c65-093a-4c60-bf77-8ebbca86c7af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='studentTitle']</value>
      <webElementGuid>e5346ce0-3d4b-4283-9aed-94728156c9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginCard']/div/div/div[3]/div/div/button/span</value>
      <webElementGuid>5ff95f9a-145f-406b-b20d-4fe3b0ab3df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password'])[1]/following::span[1]</value>
      <webElementGuid>8311a056-040c-4999-9c4b-9c1ad7dbcb43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember Me'])[1]/following::span[2]</value>
      <webElementGuid>f356097b-05cd-4c90-a3b2-8c223b72348a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Use'])[1]/preceding::span[1]</value>
      <webElementGuid>a297a540-d153-41c7-9aba-97433db4a78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Student Monthly Pass FAQs.']/parent::*</value>
      <webElementGuid>7aefb3fa-c33a-4734-8c2e-db6c84110251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button/span</value>
      <webElementGuid>173ced51-c873-44e7-9f11-0924c9e096b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'studentTitle' and (text() = 'Student Monthly Pass FAQs.' or . = 'Student Monthly Pass FAQs.')]</value>
      <webElementGuid>c7e909c1-39a0-408e-94e7-b42d91239496</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
