<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Auto Reload</name>
   <tag></tag>
   <elementGuidId>73d88264-6923-44ee-8963-37a42d7b199a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subscription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='subscription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Auto Reload&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e561dbd-2f68-4bb9-9448-5526a2d101ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedSecondary MuiButton-sizeSmall MuiButton-containedSizeSmall MuiButton-colorSecondary MuiButton-root MuiButton-contained MuiButton-containedSecondary MuiButton-sizeSmall MuiButton-containedSizeSmall MuiButton-colorSecondary css-eoy7ye</value>
      <webElementGuid>c6d60a90-39ac-46eb-87f5-c4f3ce542fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d53bf0e6-90b9-4e2d-85f3-9f848c882ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>72094a0c-9092-4cda-94d4-25f4ddeadcdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subscription</value>
      <webElementGuid>a3b7a356-a08a-4875-8b67-1e71ec30fbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Auto Reload</value>
      <webElementGuid>4ea75362-8efb-4043-b498-fdcfbfae3017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Auto Reload</value>
      <webElementGuid>5a9c839a-792c-47f8-bf20-35061cb43af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ff03a43d-37c3-44d3-8597-7ea7eaff8346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-theme</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>a4b2a2a2-fb8a-45e4-a822-c648a220a67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Auto Reload</value>
      <webElementGuid>468325ff-d686-4925-8706-18d4d85ad214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subscription&quot;)</value>
      <webElementGuid>7d77c4ca-2689-47c1-be65-6f1289a58671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='subscription']</value>
      <webElementGuid>5cdb266f-9c4f-4642-a7e4-eb22aa0260b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'subscription' and @title = 'Auto Reload' and (text() = 'Auto Reload' or . = 'Auto Reload')]</value>
      <webElementGuid>f7ae2521-c354-4bf6-aab1-46423ea8b558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboardCard']/div/div[2]/div/div[3]/button</value>
      <webElementGuid>09737960-1cee-4fdb-aa06-557831fd66cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>933d3a33-d590-4a92-958b-8329a90b174f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Tickets'])[1]/following::button[1]</value>
      <webElementGuid>c8bda3cf-d6fa-4cd2-82ca-482725253b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Value'])[1]/following::button[2]</value>
      <webElementGuid>556e47a0-d168-414c-8fca-7e28dadba857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRX. History'])[1]/preceding::button[1]</value>
      <webElementGuid>7ad2ac64-c5e3-4ac0-96ba-0f535e3f16db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Lost/Stolen'])[1]/preceding::button[2]</value>
      <webElementGuid>5a93372d-bd14-4561-98c3-23a27c56ca39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
