<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_FARE-PAY Card</name>
   <tag></tag>
   <elementGuidId>0c97b33b-0d0b-4134-ad05-87ebb2b3e5f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountFareCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='accountFareCard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;FARE-PAY Card&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e0b9cf8-d0b1-4d47-99db-86add3c60212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary MuiTab-fullWidth css-epkkkt</value>
      <webElementGuid>cd1492b4-226f-443c-9309-de65b5cd629b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1f31f4cc-8cc0-40e9-9ab4-d18fa0abd360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af1e6cfd-b166-4021-8af8-d1c30b23489e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>0291f150-2eed-438f-8bdb-60ee19f79271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f52daea-2dc3-474f-8cf3-8f6c87b8ec34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountFareCard</value>
      <webElementGuid>63c3b100-4d02-4061-b2a0-9516ff3060d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FARE-PAY Card</value>
      <webElementGuid>9c625c1b-7afb-4693-bc97-23a1eaf4c693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountFareCard&quot;)</value>
      <webElementGuid>f9bdd111-6396-46df-a02a-60c51b92f353</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='accountFareCard']</value>
      <webElementGuid>b354e371-41fc-471f-a70f-3b89608b1fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'accountFareCard' and (text() = 'FARE-PAY Card' or . = 'FARE-PAY Card')]</value>
      <webElementGuid>3a77fd5a-20bb-41d6-bd7b-e81a5392501d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div/div/div/div/button[3]</value>
      <webElementGuid>51fab46b-dc64-44e8-a6a6-92fa9c00a2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>dcd83bc2-f4ed-4fae-9a99-5756da6753c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[1]/following::button[1]</value>
      <webElementGuid>e41b9554-b96b-40c8-bb46-457eec29e45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Information'])[1]/following::button[2]</value>
      <webElementGuid>3560b97f-515f-4ed8-9659-b6fbc24c0e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tap &amp; Ride'])[1]/preceding::button[1]</value>
      <webElementGuid>5f0e6468-d2cb-4a78-8a0e-a1ea8288d977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Wallet'])[1]/preceding::button[2]</value>
      <webElementGuid>62fb49c0-68a4-4afb-8132-9fd939684547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FARE-PAY Card']/parent::*</value>
      <webElementGuid>0d1ba794-fd55-48cb-abe9-a2e9f7279bd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
