<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_train</name>
   <tag></tag>
   <elementGuidId>c739acbb-a95f-43d3-bc85-cfeb11c441f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#desc11 > span > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='desc11']/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;train&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a017279-c5d9-4410-bb2f-28ef93c7659e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.njtransit.com/tickets/train-tickets</value>
      <webElementGuid>7fec4528-9573-4665-ae4d-4b0999893a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>1a6c4414-9683-4796-b05a-117a6b998540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> train</value>
      <webElementGuid>4a9700e9-e32e-4902-b0e3-a414c996e39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desc11&quot;)/span[1]/a[1]</value>
      <webElementGuid>fd78fc50-701f-4307-b477-1aea0539b950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='desc11']/span/a</value>
      <webElementGuid>25cf1217-fade-4b9f-97b1-13c063fc0d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'train')]</value>
      <webElementGuid>6732f2cc-6fba-47f1-9429-32fae90cc75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How do I use my Student Monthly Pass?'])[1]/following::a[1]</value>
      <webElementGuid>e06eed02-1ba7-46af-b0f9-34f3332e7c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When can I purchase my student monthly pass?'])[1]/following::a[1]</value>
      <webElementGuid>44597f53-ee74-4c8a-b1fc-b78c2febd78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bus'])[2]/preceding::a[1]</value>
      <webElementGuid>1a1dd254-45bf-4dfb-acca-8a62b20b450d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='light rail'])[2]/preceding::a[2]</value>
      <webElementGuid>f6dd5bd4-84f6-4885-af83-77476b7eb790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.njtransit.com/tickets/train-tickets')])[2]</value>
      <webElementGuid>8a0d2eaa-00b6-4d24-88d0-292d282c1de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span/a</value>
      <webElementGuid>46f5cd90-2717-458a-b9f6-e20c7e90430b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.njtransit.com/tickets/train-tickets' and (text() = ' train' or . = ' train')]</value>
      <webElementGuid>f71e435b-ba3e-454c-ae11-424c961631be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
