<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buy Tickets</name>
   <tag></tag>
   <elementGuidId>9b409d53-8242-4d9f-afa1-4e8045885d11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buyTicketBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buyTicketBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Buy Tickets&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>193ee876-467c-49ab-b9a3-bc040569ffee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedSecondary MuiButton-sizeSmall MuiButton-containedSizeSmall MuiButton-colorSecondary MuiButton-root MuiButton-contained MuiButton-containedSecondary MuiButton-sizeSmall MuiButton-containedSizeSmall MuiButton-colorSecondary css-eoy7ye</value>
      <webElementGuid>e95ef0a5-d37e-4cc0-bc5c-88697e916237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>619ed8fd-a38d-42c5-8f50-b6421ba6d360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>53512067-42e9-4a0a-b4b5-89bb5d0cfce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buyTicketBtn</value>
      <webElementGuid>7c017917-9ecd-495c-aa6f-dd22dac73b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buy Tickets</value>
      <webElementGuid>f92b82d8-dd7e-4496-b260-49687750c1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Buy Tickets</value>
      <webElementGuid>91a4d7e1-7eb2-4474-9244-263d5d6a7750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>761977bd-a0f2-43d0-a70e-ed13a11cfa17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-theme</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>cff27d4c-79bb-436c-a2c4-eb87b2de7277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy Tickets</value>
      <webElementGuid>a05988ab-5fd6-4145-80ba-ec93a14cc57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buyTicketBtn&quot;)</value>
      <webElementGuid>9cb10366-b14c-4ac4-83f0-6ef64d3b6eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buyTicketBtn']</value>
      <webElementGuid>89b45260-0ec6-42d4-9bcc-ce0e0e8f096a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'buyTicketBtn' and @title = 'Buy Tickets' and (text() = 'Buy Tickets' or . = 'Buy Tickets')]</value>
      <webElementGuid>bb190138-3ad9-4437-baf8-ddb530b4ad8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboardCard']/div/div[2]/div/div[2]/button</value>
      <webElementGuid>a0505894-34f7-4847-b235-d52589ff4d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>3a80716a-702f-44ba-8604-05bb650e9d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Value'])[1]/following::button[1]</value>
      <webElementGuid>5f0e4cb3-26cf-4e01-8bb1-5b780d4f4797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNREGISTER CARD'])[1]/following::button[2]</value>
      <webElementGuid>195a84c5-5af4-49d8-a019-76a0f2d0bef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Reload'])[2]/preceding::button[1]</value>
      <webElementGuid>48c6c7ad-bbda-40a9-800a-39f0428362b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRX. History'])[1]/preceding::button[2]</value>
      <webElementGuid>bfcb7355-8a5e-4b50-a782-d15b19d48203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buy Tickets']/parent::*</value>
      <webElementGuid>e33d29df-429c-4902-8296-a6b8e274cf8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
