<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Bus Tickets</name>
   <tag></tag>
   <elementGuidId>5617fae5-4854-4395-a1bb-7a2a14e593fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.ff-secondary--bold.mb-3.text--cerize</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/main/article/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Bus Tickets&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>9e18e4a3-6d45-42fa-a846-8ff1f2537826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ff-secondary--bold mb-3 text--cerize</value>
      <webElementGuid>a1d5e51a-2331-4e22-876a-38cb5469a8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-be-app</name>
      <type>Main</type>
      <value>processed</value>
      <webElementGuid>fabdcbd0-cfaa-4859-8fe8-3956271db466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bus Tickets</value>
      <webElementGuid>3046f449-925a-424d-bf23-b4c84c404160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/main[@class=&quot;clearfix pt-md-2 container container-fluid&quot;]/article[1]/h1[@class=&quot;ff-secondary--bold mb-3 text--cerize&quot;]</value>
      <webElementGuid>9f57464e-126b-4deb-a923-39dba50ae96e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/main/article/h1</value>
      <webElementGuid>292dfffa-9a02-4364-a3fa-f658ff2b3932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(opens in a new window)'])[45]/following::h1[1]</value>
      <webElementGuid>e0c60ae1-330d-4e8a-b5df-36465bc01e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One-Way Tickets'])[1]/preceding::h1[1]</value>
      <webElementGuid>0d4b0ebd-82e9-4e2f-8ee7-bb2b52207115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>dc8013db-aa12-4da5-9a38-37bd1f4fc56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Bus Tickets' or . = 'Bus Tickets')]</value>
      <webElementGuid>5b8ff869-59ff-4c8d-9c8e-6dc286fa2293</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
