<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FarePayCardNumberXpath</name>
   <tag></tag>
   <elementGuidId>823dbbec-c8b9-4c2e-8fe2-0f52a73be9fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id='cards']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
