<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passAmountWhileAutoReload</name>
   <tag></tag>
   <elementGuidId>9703858e-8406-487a-aefc-02eda1c83afa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>((//h3[@id='subtitle']//following-sibling::div/fieldset/child::*)[1]/div/div/label/span)[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
