<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_ZipPostal Code is too short</name>
   <tag></tag>
   <elementGuidId>864427db-0f57-4718-a655-a2a6acf238af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zipCode-error-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='zipCode-error-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Zip/Postal Code is too short&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>094f210c-a9e7-4f01-ac3b-870bfbe230bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeSmall MuiFormHelperText-contained MuiFormHelperText-filled css-18emikf</value>
      <webElementGuid>51f2fdc6-e597-45a5-8437-144634e1878e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zipCode-error-text</value>
      <webElementGuid>ad68f991-2362-473e-a9ff-ec880b6cb510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>3512a42f-f2b3-43b1-88ff-fd8e0cd6e690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zip/Postal Code is too short</value>
      <webElementGuid>b2c62e55-08d9-435e-b5f6-6864716646d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zipCode-error-text&quot;)</value>
      <webElementGuid>b40b1a48-9c8f-4c0a-894e-d33ea72440d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='zipCode-error-text']</value>
      <webElementGuid>e5a81e03-f011-45a0-b6a4-8fa32985e1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div/div/div[6]/div/div/div/div[2]/p</value>
      <webElementGuid>54ffe85e-6756-4220-b452-de15566f6ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[9]/following::p[1]</value>
      <webElementGuid>be180784-18fe-495c-b989-63d7fede95ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip/Postal Code'])[1]/following::p[1]</value>
      <webElementGuid>d421b849-a175-40b3-813e-275016fb59a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Of Birth (MM/DD)'])[1]/preceding::p[1]</value>
      <webElementGuid>a8897a24-3eee-4bc1-95c6-7e2aaf639e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[10]/preceding::p[1]</value>
      <webElementGuid>9a19ee20-15e6-4be0-8116-25723d208791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Zip/Postal Code is too short']/parent::*</value>
      <webElementGuid>65bceaad-a71f-44bc-9a7d-1a19788efefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>9b5337e3-ae60-4844-a8ac-0ce461e1a5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'zipCode-error-text' and (text() = 'Zip/Postal Code is too short' or . = 'Zip/Postal Code is too short')]</value>
      <webElementGuid>5725ad38-e805-46a2-9aa5-6b875416ed95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
