<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Us_flex-auto rounded-md borde_d34ab1_1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>a1642446-078e-4e27-a965-d01cc39c3d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='il']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;view-this-mailbox&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d027ca36-fea9-451f-841d-f00cef1a9667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd39bd68-ba00-42b4-b0fe-7271b0fc264c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>view-this-mailbox</value>
      <webElementGuid>f8686530-468b-432e-b15e-dd247475eb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>effefdc3-466b-4bd7-80c5-01bbd3516995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-auto rounded-md border-stone-400 bg-white py-2 px-2 text-right text-base text-stone-900 placeholder-stone-400 focus:border-white focus:placeholder-stone-300 focus:ring-[3px] focus:ring-rose-500/80 dark:border-stone-500 dark:bg-stone-800/95 dark:text-stone-50 dark:focus:border-stone-900 dark:focus:placeholder-stone-600 dark:focus:ring-rose-600/80</value>
      <webElementGuid>32f1eb8d-9d97-4d2b-a73b-4a6b4a29c3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>il</value>
      <webElementGuid>9bb6265d-7e68-4043-a032-ca23fa399549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;flex flex-wrap items-center md:container md:mx-auto md:flex-nowrap md:px-4 md:py-2 lg:px-8&quot;]/div[@class=&quot;hidden absolute top-16 z-10 w-full flex-none bg-stone-100 pt-4 pb-16 dark:bg-stone-800 md:relative md:top-auto md:flex md:w-auto md:flex-auto md:items-center md:bg-transparent md:pt-0 md:pb-0 md:pl-4&quot;]/form[@class=&quot;px-8 md:px-0 lg:max-w-[50ch] flex flex-auto flex-wrap md:flex-nowrap&quot;]/div[@class=&quot;flex flex-auto flex-nowrap items-center&quot;]/input[@class=&quot;flex-auto rounded-md border-stone-400 bg-white py-2 px-2 text-right text-base text-stone-900 placeholder-stone-400 focus:border-white focus:placeholder-stone-300 focus:ring-[3px] focus:ring-rose-500/80 dark:border-stone-500 dark:bg-stone-800/95 dark:text-stone-50 dark:focus:border-stone-900 dark:focus:placeholder-stone-600 dark:focus:ring-rose-600/80&quot;]</value>
      <webElementGuid>cafbd3a1-56b2-4108-a750-1a5f983292dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='il']</value>
      <webElementGuid>431077f3-22d3-4337-8e01-7418172ed9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'view-this-mailbox']</value>
      <webElementGuid>9377820f-7846-448c-9c8c-d7bcac99abd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div/div[3]/form/div/input</value>
      <webElementGuid>34bfda2c-c67c-4353-97c0-52ec38afc601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bc3a7b11-3631-4f86-9ac0-d3b61dc94431</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
