<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Us_flex-auto rounded-md borde_d34ab1_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>38d0b3f7-e5d2-44f0-9572-615c243c4770</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='735']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;view-this-mailbox&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c0ba6a8-c2d4-460b-ba08-556f6041e1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fef0c9bd-4f5a-4145-acda-29613d6feef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>view-this-mailbox</value>
      <webElementGuid>ea0c1f06-d612-4f21-99af-ea7c3ac6be97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>3cb09293-2132-4bc5-82a7-22b6ce3731b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-auto rounded-md border-stone-400 bg-white py-2 px-2 text-right text-base text-stone-900 placeholder-stone-400 focus:border-white focus:placeholder-stone-300 focus:ring-[3px] focus:ring-rose-500/80 dark:border-stone-500 dark:bg-stone-800/95 dark:text-stone-50 dark:focus:border-stone-900 dark:focus:placeholder-stone-600 dark:focus:ring-rose-600/80</value>
      <webElementGuid>a6a5aa61-ea75-4e0f-8ea6-937d9b8115ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>735</value>
      <webElementGuid>e6f15b90-febf-4dd7-8b20-5cd94fb3e1be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;flex flex-wrap items-center md:container md:mx-auto md:flex-nowrap md:px-4 md:py-2 lg:px-8&quot;]/div[@class=&quot;hidden absolute top-16 z-10 w-full flex-none bg-stone-100 pt-4 pb-16 dark:bg-stone-800 md:relative md:top-auto md:flex md:w-auto md:flex-auto md:items-center md:bg-transparent md:pt-0 md:pb-0 md:pl-4&quot;]/form[@class=&quot;px-8 md:px-0 lg:max-w-[50ch] flex flex-auto flex-wrap md:flex-nowrap&quot;]/div[@class=&quot;flex flex-auto flex-nowrap items-center&quot;]/input[@class=&quot;flex-auto rounded-md border-stone-400 bg-white py-2 px-2 text-right text-base text-stone-900 placeholder-stone-400 focus:border-white focus:placeholder-stone-300 focus:ring-[3px] focus:ring-rose-500/80 dark:border-stone-500 dark:bg-stone-800/95 dark:text-stone-50 dark:focus:border-stone-900 dark:focus:placeholder-stone-600 dark:focus:ring-rose-600/80&quot;]</value>
      <webElementGuid>df57bb7e-38f6-46bf-9a16-080ab089faed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='735']</value>
      <webElementGuid>20ee5aaa-b1a8-4793-b04f-11e1d6edf48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'view-this-mailbox']</value>
      <webElementGuid>0e84caf3-d42e-400d-a1dc-b433d3148104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div/div[3]/form/div/input</value>
      <webElementGuid>ef2e166d-a71f-41a7-be89-56e45eaab0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f25088ee-d63f-4991-857a-918b8a83601b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
