<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_afillfb8e2cTicket Transactions</name>
   <tag></tag>
   <elementGuidId>ef4974f1-fc29-427a-82da-1026938208b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ticketTransTab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ticketTransTab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Ticket Transactions&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c4056ef-2a53-41d4-8854-da2cb311f389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-labelIcon MuiTab-textColorPrimary Mui-selected css-1k1tvsy</value>
      <webElementGuid>9172cf65-1872-4de6-80f3-db3b5bf10b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a998c26a-5167-4a01-91d6-ac60226b26a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d179b76b-6eac-4192-b498-792498a3582b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>27dd259b-bb6f-4741-af01-d0470621e450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e074c807-d7ed-40bb-8dfc-6f872b21d7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ticketTransTab</value>
      <webElementGuid>2271a0e7-7807-4e0d-b6e8-e143f5921e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.a{fill:#fb8e2c}Ticket Transactions</value>
      <webElementGuid>e50c7070-baa7-4bed-8b31-0df34c1834b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ticketTransTab&quot;)</value>
      <webElementGuid>0a723251-f351-4c5d-a8c2-4f61d2b95afe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ticketTransTab']</value>
      <webElementGuid>1f362ab5-7862-4a91-81c7-bda91f7cc168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'ticketTransTab' and (text() = '.a{fill:#fb8e2c}Ticket Transactions' or . = '.a{fill:#fb8e2c}Ticket Transactions')]</value>
      <webElementGuid>5ded8f70-d231-460a-a361-a8c98a2c01c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentTabs']/div/div/button</value>
      <webElementGuid>57b0fbc5-f10a-42fc-91cb-b14dfb978fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/button</value>
      <webElementGuid>2aae690d-2882-4be9-8b89-6a4c42ab87f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/following::button[1]</value>
      <webElementGuid>8256e299-568b-4d3d-a491-8b1e67475b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select FARE-PAY Card:'])[2]/following::button[1]</value>
      <webElementGuid>eb98aaac-5e5f-4fc3-9f4b-632255cd943c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Value Transactions'])[1]/preceding::button[1]</value>
      <webElementGuid>4a2c92fc-b1e4-46b2-b2fc-29e2f0c05378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trip History'])[1]/preceding::button[2]</value>
      <webElementGuid>9c194184-6790-4bfe-ad30-f6eafb640643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ticket Transactions']/parent::*</value>
      <webElementGuid>2cf2ef33-9d99-4529-b22d-d32111b92ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
