<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Name_input.Employee_Name__c</name>
   <tag></tag>
   <elementGuidId>3fd68192-e66f-4b6f-b7ad-eb43dd303318</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='input.Employee_Name__c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;input.Employee_Name__c&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;input\.Employee_Name__c&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>701079e7-bda8-4274-86d4-d8427deb9522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0ab1c0d1-6461-466e-9e2e-210c9fc93bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input.Employee_Name__c</value>
      <webElementGuid>f4b51ba1-e640-40d9-aaa4-8f3105cc83cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3705e949-6449-4dd4-a4e3-22667d51fd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>aa1a4124-9cbf-4916-a16b-764faa4fc48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;container&quot;]/form[@class=&quot;form-edit&quot;]/fieldset[2]/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-sm form-group&quot;]/div[1]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>42aa92f9-425a-40e7-bb34-3ef37b81f267</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='input.Employee_Name__c']</value>
      <webElementGuid>1bea2e45-edcc-460b-a6c4-531c1d028df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/form/fieldset[2]/div/div[2]/div/input</value>
      <webElementGuid>b099fc39-f372-438c-bb3e-999c4531ff44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div[2]/div/input</value>
      <webElementGuid>2a3e1885-9f39-4ed2-807c-369b80357fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input.Employee_Name__c' and @type = 'text']</value>
      <webElementGuid>912a117a-4f33-456a-8616-c4f2ada9c372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
