<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_input.Customer_First_Name__c</name>
   <tag></tag>
   <elementGuidId>e5dee33e-5258-4ef3-a903-a4b93c6e438d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='input.Customer_First_Name__c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;input.Customer_First_Name__c&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;input\.Customer_First_Name__c&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07762c41-cab0-48d3-989b-6440f3e5e4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5e6830ea-cd1f-4151-a4de-8ca3a7b61113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input.Customer_First_Name__c</value>
      <webElementGuid>1230f9b6-6bd4-40cc-aa1d-2a3406406181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>a8ac2f64-1687-4eda-9464-11de5b4358fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b072642e-d514-4484-b041-2efbe0cf899b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e293d089-6276-4487-a24e-e3b6043f7d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;container&quot;]/form[@class=&quot;form-edit&quot;]/fieldset[3]/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-sm form-group&quot;]/div[1]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>b86dbc25-26f2-47aa-ac5f-6e9e28acaada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='input.Customer_First_Name__c']</value>
      <webElementGuid>9d69b944-c814-4449-bda5-62c627476a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/form/fieldset[3]/div/div/div/input</value>
      <webElementGuid>90b24bec-11f2-45bc-bc7e-605e4acd00e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div/input</value>
      <webElementGuid>7d53320d-9170-4883-a95c-9e848a840a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input.Customer_First_Name__c' and @type = 'text']</value>
      <webElementGuid>30dfaa4b-0002-4b86-897f-059307c47b68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
