<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_For re-enrollment please try login into t_f6e7fa</name>
   <tag></tag>
   <elementGuidId>198c1b0c-cea2-475c-ac97-a0251698db79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='desc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;For re-enrollment please try login into the application using MyTix Student Mont&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d74412d0-c326-4eb6-b54a-456977a63faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-inherit css-1vhohya</value>
      <webElementGuid>31c61c1c-a2dd-4ae1-8548-837300c419ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>desc</value>
      <webElementGuid>d0168964-2d7f-4e6e-9d0f-c8331e79526d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>For re-enrollment please try login into the application using MyTix Student Monthly Pass – Account Management option from your university portal.</value>
      <webElementGuid>6f232d60-551a-4f79-9f62-7921cc0846e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desc&quot;)</value>
      <webElementGuid>fee94881-f5c0-4938-b1e8-a692f3559f58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='desc']</value>
      <webElementGuid>af375d22-f86b-4528-8b20-2c97bd819cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/p[2]</value>
      <webElementGuid>d3da35fd-d4fe-4d75-b195-0e9ade9c3aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration Failed'])[1]/following::p[2]</value>
      <webElementGuid>57bc969e-ef71-49f6-a54b-27ac0719642f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::p[2]</value>
      <webElementGuid>e2a850c1-66d2-4eb4-9c49-5363026961ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help &amp; Support'])[1]/preceding::p[1]</value>
      <webElementGuid>bef3c5e8-fdf2-48bf-ade0-27b46ff41fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/preceding::p[1]</value>
      <webElementGuid>01004cfa-b746-47c7-b7e8-5902d877b4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='For re-enrollment please try login into the application using MyTix Student Monthly Pass – Account Management option from your university portal.']/parent::*</value>
      <webElementGuid>a5ab795f-5cd5-407a-a88b-986cc1f5ed0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>db21ec20-64eb-4df0-afcc-b26c7899b8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'desc' and (text() = 'For re-enrollment please try login into the application using MyTix Student Monthly Pass – Account Management option from your university portal.' or . = 'For re-enrollment please try login into the application using MyTix Student Monthly Pass – Account Management option from your university portal.')]</value>
      <webElementGuid>93703e80-13ef-4f1e-b16e-751fb561c00a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
