<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Invalid email domain. The email that you _f813ce</name>
   <tag></tag>
   <elementGuidId>8c3045ad-2e61-487e-97c3-1741efd7e19f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='subDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Invalid email domain. The email that you entered does not match with the school'&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5577c094-97c0-4706-8a70-b4e5faf43654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 css-1hocgsk</value>
      <webElementGuid>0c179479-f5af-4975-9a48-a062a1d1bc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subDesc</value>
      <webElementGuid>6ee906fa-56d7-4973-92fb-44ed8584e9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid email domain. The email that you entered does not match with the school's registers office.</value>
      <webElementGuid>cc0299c5-ae61-48c9-9136-13e40ece8772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subDesc&quot;)</value>
      <webElementGuid>866f6114-3bd8-446a-9a42-fcd542602ac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='subDesc']</value>
      <webElementGuid>0c173404-1c71-4513-9e59-d3fb74520184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/p</value>
      <webElementGuid>28ae3b70-8454-4763-a7dc-6d88a10db367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration Failed'])[1]/following::p[1]</value>
      <webElementGuid>06eeaae5-e928-43c1-930b-74f37dc4853f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::p[1]</value>
      <webElementGuid>def22b9f-a8ea-42e1-ac75-43a1e40aa617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help &amp; Support'])[1]/preceding::p[2]</value>
      <webElementGuid>ab94a8f8-72d0-47aa-88bb-9849920f8555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/preceding::p[2]</value>
      <webElementGuid>576ddd75-8774-43bd-bc1d-a52c8603b4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>f4720765-f724-4a39-8b93-a2fc4ace994f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'subDesc' and (text() = concat(&quot;Invalid email domain. The email that you entered does not match with the school&quot; , &quot;'&quot; , &quot;s registers office.&quot;) or . = concat(&quot;Invalid email domain. The email that you entered does not match with the school&quot; , &quot;'&quot; , &quot;s registers office.&quot;))]</value>
      <webElementGuid>1d6cc86d-d291-40c2-af4f-0d21e160e31a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
