<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Verification link has been sent to fsdfsm_299f1e</name>
   <tag></tag>
   <elementGuidId>9df64cb0-2382-430b-961d-f1bafeb19cda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='desc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Verification link has been sent to fsdfs@maildrop.cc Please allow up to 5 minute&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7bdb9cb3-c346-4811-a000-ef23bf34c70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-inherit css-14jw1cy</value>
      <webElementGuid>ff8e814f-dcc3-4b02-8fb8-9fd03eca0785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>desc</value>
      <webElementGuid>c3b2ad4d-6e66-4110-beaf-b1b1ebd9ddf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verification link has been sent to fsdfs@maildrop.cc Please allow up to 5 minutes for the verification email to arrive.</value>
      <webElementGuid>b9e0f58a-4a52-4f96-a04d-7cbec9d4a885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desc&quot;)</value>
      <webElementGuid>ad8a4863-4610-4e47-8a7e-9f4336dfd4f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='desc']</value>
      <webElementGuid>19958a75-8d5b-4ef1-9193-ab2c1ca305be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/p</value>
      <webElementGuid>9ac9200e-6be4-4c58-ba6e-68ce00e68e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration Successful'])[1]/following::p[1]</value>
      <webElementGuid>9b734d6d-4ab0-4aa1-8b29-392c43329496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::p[1]</value>
      <webElementGuid>96a479b8-48b7-43fd-b830-f73f9e35f7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regenerate'])[1]/preceding::p[2]</value>
      <webElementGuid>38af1378-80ab-42a9-84ac-6e48de65a57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help &amp; Support'])[1]/preceding::p[2]</value>
      <webElementGuid>a04253b2-04fc-4f20-82cb-324cd138ecb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verification link has been sent to']/parent::*</value>
      <webElementGuid>485af4eb-9ba8-45a3-a4c7-45d08e2aec2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>9b835533-7b9f-4e72-a1c8-058eb37231fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'desc' and (text() = 'Verification link has been sent to fsdfs@maildrop.cc Please allow up to 5 minutes for the verification email to arrive.' or . = 'Verification link has been sent to fsdfs@maildrop.cc Please allow up to 5 minutes for the verification email to arrive.')]</value>
      <webElementGuid>c5d01758-0096-44d0-b75d-2582d3ba97b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
