<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1. Fill in all required fields on the _8c4dec</name>
   <tag></tag>
   <elementGuidId>21c3aff9-d1ce-4004-af7f-e3901d7de5b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#studentRegDesc1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='studentRegDesc1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1. Fill in all required fields on the registration form.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d07e9dcc-ef17-412e-b538-35e0792a5ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-subText css-1c09nwh</value>
      <webElementGuid>75000a3c-6820-404a-b6c9-854dbf12d3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>studentRegDesc1</value>
      <webElementGuid>0c6dbcc6-2daa-46e8-9ba0-54c76dd9e2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1. Fill in all required fields on the registration form.</value>
      <webElementGuid>cdffb405-908f-4281-b5bb-a0902214ad3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;studentRegDesc1&quot;)</value>
      <webElementGuid>98800c22-4b6b-492d-a298-a2c355d95fd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='studentRegDesc1']</value>
      <webElementGuid>9c30f113-b156-4a4b-afb1-adeb46399426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div/div[2]/div/ul/li/span</value>
      <webElementGuid>1981c813-54a2-4d45-9610-0dcb99a82c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[10]/following::span[1]</value>
      <webElementGuid>8e0b42e6-958a-460c-b08c-8d6a4a8fe8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Of Birth (MM/DD)'])[1]/following::span[2]</value>
      <webElementGuid>b6247b31-3de4-424c-a2fb-0c12f1e01f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student Monthly Pass FAQs.'])[1]/preceding::span[3]</value>
      <webElementGuid>ea911b1f-9f85-4b22-a593-980124056bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Use'])[1]/preceding::span[4]</value>
      <webElementGuid>5c6cfd23-a4a9-496f-85c8-e4495996f12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1. Fill in all required fields on the registration form.']/parent::*</value>
      <webElementGuid>82d0b849-3c48-431a-afaf-b13eb2996387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>124d69b8-2551-4731-907c-9b2200624f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'studentRegDesc1' and (text() = '1. Fill in all required fields on the registration form.' or . = '1. Fill in all required fields on the registration form.')]</value>
      <webElementGuid>7fedf4b0-dadc-41ab-adde-4a66b820f769</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
