<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Denotes required fields</name>
   <tag></tag>
   <elementGuidId>449437ca-d497-44ac-a7c7-8a3a926503c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#requiredNote</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='requiredNote']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;* Denotes required fields&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b9d0a9e-3fc2-459d-9955-ab7dd6942c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-desc css-1amlqwo</value>
      <webElementGuid>7f33774e-0e47-4712-949d-e2a0a8de8522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requiredNote</value>
      <webElementGuid>b77bf1b9-65a4-46ef-8b0f-2a772b185a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>* Denotes required fields</value>
      <webElementGuid>6cc51e0a-b53e-4f23-b465-365248e4446c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requiredNote&quot;)</value>
      <webElementGuid>e1cee835-9e27-4b94-b696-e5f0969c1156</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='requiredNote']</value>
      <webElementGuid>f2ddc41d-c068-4c96-b5ff-5dc2c1bdd94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div/div/div/span</value>
      <webElementGuid>22ec226c-8028-4773-a4cd-89713e76f8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create your Mobile MyTix Student Monthly Pass account with these simple steps.'])[1]/following::span[1]</value>
      <webElementGuid>a45af83d-1301-4ec1-9b27-378b80dfb105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Student Registration'])[1]/following::span[2]</value>
      <webElementGuid>698f4653-7b7a-46ed-b991-561e3171080f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::span[2]</value>
      <webElementGuid>bc0d5f1f-05e5-4cad-926a-9a920ea8d53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Denotes required fields']/parent::*</value>
      <webElementGuid>fbfc6063-3906-4c8a-8cf8-6839d1d7ba0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/span</value>
      <webElementGuid>3d157922-5350-41a5-84d2-b43b63ea70d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'requiredNote' and (text() = '* Denotes required fields' or . = '* Denotes required fields')]</value>
      <webElementGuid>ca78c1a4-a019-4f8e-b0ec-769af1367458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
