<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2025  NJ TRANSIT All Rights Reserved</name>
   <tag></tag>
   <elementGuidId>61e2b5ee-5aad-4863-ac46-2328f5cb3674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#footerDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='footerDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;2025 © NJ TRANSIT All Rights Reserved.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d46203b4-2b66-4eaf-a94e-4031dd8cb7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-footerText css-sbt24a</value>
      <webElementGuid>f28a0ade-874c-4333-b743-b90aa7bfd65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>footerDesc</value>
      <webElementGuid>069b3e4f-ba73-4b8c-9fe7-aa2a1a17677e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2025 © NJ TRANSIT All Rights Reserved.</value>
      <webElementGuid>aadaf618-c9a6-4abe-b5c5-06f52830dde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footerDesc&quot;)</value>
      <webElementGuid>cbcfc04a-fde8-4a65-8434-03492c4b270d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='footerDesc']</value>
      <webElementGuid>193af401-d710-417a-af67-cc0db89a8d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footerDescBox']/span</value>
      <webElementGuid>1825b62c-071f-4781-bf21-1d09b40fc85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='submit'])[1]/following::span[1]</value>
      <webElementGuid>468271cd-f95c-45c2-85c5-1222c4905df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help &amp; Support'])[1]/preceding::span[1]</value>
      <webElementGuid>563a5a21-77d1-4919-a353-fb82d9977755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/preceding::span[1]</value>
      <webElementGuid>3f253b38-343f-464c-87b9-80a63b3fde07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2025']/parent::*</value>
      <webElementGuid>35420082-ab63-4b44-b5c6-d18862971d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div/div/div/span</value>
      <webElementGuid>9709337b-3bb0-40cc-9ab6-0384acab832a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'footerDesc' and (text() = '2025 © NJ TRANSIT All Rights Reserved.' or . = '2025 © NJ TRANSIT All Rights Reserved.')]</value>
      <webElementGuid>5a1a20da-0e04-4cc6-be8d-435d85dcddc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
