<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_date_input - admin</name>
   <tag></tag>
   <elementGuidId>a8bb439e-65e4-4b23-aa42-0e8603c3c3d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/button[7]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@tabindex = '0' and @type = 'button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;15&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dde8f1b6-a73d-46aa-acdf-f38310ffb5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiPickersDay-root MuiPickersDay-dayWithMargin css-1ynnjy6</value>
      <webElementGuid>424b2915-7f35-4c35-b694-26682f5eb91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>10426d73-fba6-41a5-b225-3c998402dfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30ac655a-8bac-4160-8a88-d90907b7da91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>86384f43-a828-4819-b165-7ea46bfee055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-timestamp</name>
      <type>Main</type>
      <value>1741977000000</value>
      <webElementGuid>21d089f4-a6d4-4843-9aed-06e6ffd84226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>9f2d3762-d4db-40d9-acfd-b2d4551fcf46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>046353b7-b519-4390-8687-483820ee4f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>d5487c76-30bb-4b2b-8940-f609dce0c993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiPopper-root MuiPickersPopper-root css-1mtsuo7&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation8 MuiPickersPopper-paper css-1c08mdw&quot;]/div[@class=&quot;MuiPickersLayout-root css-192l38i&quot;]/div[@class=&quot;MuiPickersLayout-contentWrapper css-lz05jy&quot;]/div[@class=&quot;MuiDateCalendar-root css-5oi4td&quot;]/div[@class=&quot;MuiPickersFadeTransitionGroup-root MuiDateCalendar-viewTransitionContainer css-1h73gvd&quot;]/div[1]/div[@class=&quot;MuiDayCalendar-root css-0&quot;]/div[@class=&quot;MuiPickersSlideTransition-root MuiDayCalendar-slideTransition css-1xuxf2l&quot;]/div[@class=&quot;MuiDayCalendar-monthContainer css-i6bazn&quot;]/div[@class=&quot;MuiDayCalendar-weekContainer css-mvmu1r&quot;]/button[@class=&quot;MuiButtonBase-root MuiPickersDay-root MuiPickersDay-dayWithMargin css-1ynnjy6&quot;]</value>
      <webElementGuid>5016bc46-f85b-40c7-8fa8-6904f3d0b7f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[25]</value>
      <webElementGuid>228d78bf-6ba6-47eb-b522-dc9ec191802c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::button[15]</value>
      <webElementGuid>362eaf14-55e7-4a5f-97a9-3013e099c90b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::button[15]</value>
      <webElementGuid>051bf9f3-836e-411e-a102-95119f5ea13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='15']/parent::*</value>
      <webElementGuid>ff7dea1d-0d6d-46c5-a698-fbb3be92877e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[7]</value>
      <webElementGuid>500a8fe9-ac7a-4d6b-8c5b-357c024cfa5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '15' or . = '15')]</value>
      <webElementGuid>6004f328-225f-452d-8433-0e082d4b562a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
